[package]
name = "costart"
version = "1.0.0"
authors = []

[addresses]
first = "_"


[dev-addresses]

[dependencies.AptosFramework]
#git = "https://github.com/aptos-labs/aptos-core.git"
#rev = "mainnet"
#subdir = "aptos-move/framework/aptos-framework"
local = "../aptos-core/aptos-move/framework/aptos-framework"

[dev-dependencies]
